"""
app.py — Lexrisk: AI-powered predatory clause scanner
Run: streamlit run app.py
"""

import logging
import os
import sys
import PyPDF2
import streamlit as st
from dotenv import load_dotenv

# ── 1. Page Config (MUST BE FIRST STREAMLIT COMMAND) ──────────────────────────
st.set_page_config(
    page_title="LexRisk ⚖️",
    page_icon="⚖️",
    layout="centered",
    initial_sidebar_state="expanded",
)

# ── 2. Local Imports & Config ─────────────────────────────────────────────────
# Add current directory to path so analyzer and demo_data can be found
sys.path.insert(0, os.path.dirname(__file__))
from analyzer import ClauseAnalyzer
from demo_data import DEMOS  

load_dotenv()
logging.basicConfig(level=os.getenv("LOG_LEVEL", "INFO"))

# ── 3. Session State Initialization ───────────────────────────────────────────
if 'contract_text' not in st.session_state:
    st.session_state.contract_text = ""
if 'demo_active' not in st.session_state:
    st.session_state.demo_active = False

# ── 4. Styles ─────────────────────────────────────────────────────────────────
st.markdown("""
<style>
    .risk-critical { color: #ff4444; font-weight: bold; font-size: 1.5rem; }
    .risk-high     { color: #ff8800; font-weight: bold; font-size: 1.5rem; }
    .risk-medium   { color: #ffcc00; font-weight: bold; font-size: 1.5rem; }
    .risk-low      { color: #44cc44; font-weight: bold; font-size: 1.5rem; }
    .clause-card   { background: #1a1a2e; padding: 1rem; border-radius: 8px; margin: 0.5rem 0; }
</style>
""", unsafe_allow_html=True)

# ── 5. Sidebar Demos (Zero Latency) ───────────────────────────────────────────
st.sidebar.markdown("### ⚡ Instant Demos")
st.sidebar.caption("Pre-computed to bypass API limits during launch.")

def load_frozen_demo(demo_key):
    st.session_state.contract_text = DEMOS[demo_key]['text']
    st.session_state.demo_active = True

if st.sidebar.button("📱 Analyze TikTok ToS", use_container_width=True):
    load_frozen_demo('tiktok')
if st.sidebar.button("🐦 Analyze X ToS", use_container_width=True):
    load_frozen_demo('x_tos')
if st.sidebar.button("🏋️ Analyze Gym Contract", use_container_width=True):
    load_frozen_demo('gym')
if st.sidebar.button("💼 Analyze Startup NDA", use_container_width=True):
    load_frozen_demo('nda')

# ── 6. Main Header ────────────────────────────────────────────────────────────
st.title("⚖️ Lexrisk")
st.caption("AI Safety Gauge for Predatory Legal Contracts — *Building in public, Day 5*")
st.warning("""
⚠️ **Disclaimer:** Lexrisk is an AI analysis tool, not a substitute for legal advice. 
Results are generated by AI and may contain errors. Always consult a qualified attorney 
before making decisions based on this analysis. By using this tool, you acknowledge that 
Babylon Technologies provides this service "as is" without warranties.
""")
st.divider()

# ── 7. PDF Uploader (World-Class Feature) ─────────────────────────────────────
st.markdown("### 📄 Upload a Contract (PDF)")
uploaded_file = st.file_uploader("Drag and drop a PDF file here to scan", type="pdf")

if uploaded_file is not None:
    try:
        pdf_reader = PyPDF2.PdfReader(uploaded_file)
        extracted_text = ""
        for page in pdf_reader.pages:
            extracted_text += page.extract_text() + "\n"
        
        # Inject the PDF text directly into the scanner's session state
        st.session_state.contract_text = extracted_text
        st.session_state.demo_active = False # Disable demo bypass for new uploads
        st.success("✅ PDF Extracted Successfully! Scroll down to review and analyze.")
    except Exception as e:
        st.error(f"Error reading PDF: {e}")

st.markdown("---")

# ── 8. Main Input Area ────────────────────────────────────────────────────────
contract_text = st.text_area(
    "Paste your contract or Terms of Service here",
    value=st.session_state.contract_text,
    height=300,
    placeholder="Paste any TOS, contract, or legal agreement...",
)

# Sync the text area back to session state if the user types manually
if contract_text != st.session_state.contract_text:
    st.session_state.contract_text = contract_text
    st.session_state.demo_active = False  # They edited it, so it's no longer a pure demo

# ── 9. Clickwrap & Analysis Trigger ───────────────────────────────────────────
st.markdown("---")
agreed = st.checkbox(
    "I understand Lexrisk is an AI tool and not a substitute for professional legal advice. "
    "I agree to the Terms of Service and Privacy Policy."
)

col1, col2 = st.columns([1, 2])
with col1:
    analyze_btn = st.button(
        "🔍 Analyze", 
        type="primary", 
        use_container_width=True, 
        disabled=not agreed
    )

if not agreed:
    st.info("💡 Please check the box above to enable the analysis.")

# ── 10. Core Analysis Logic ───────────────────────────────────────────────────
if analyze_btn and st.session_state.contract_text.strip():
    try:
        # Check if we are running a frozen demo or a live API call
        if st.session_state.demo_active:
            # Bypass Groq entirely, use the frozen data based on matching text
            demo_match = next((d['analysis'] for d in DEMOS.values() if d['text'] == st.session_state.contract_text), None)
            if demo_match:
                result_data = demo_match
                # Reconstruct an object-like structure to match your analyzer output
                class DummyResult: pass
                result = DummyResult()
                result.risk_score = result_data['risk_score']
                result.risk_level = result_data['risk_level']
                result.summary = result_data['summary']
                result.recommendation = result_data['recommendation']
                result.disclaimer = "Lexrisk is an AI-powered assistant, not a legal professional. This analysis is for informational purposes only and does not constitute legal advice or an attorney-client relationship."
                
                class DummyClause:
                    def __init__(self, c):
                        self.category = c['category']
                        self.severity = c['severity']
                        self.clause_text = c['clause_text']
                        self.plain_english = c['plain_english']
                        self.red_flag = c['red_flag']
                
                result.flagged_clauses = [DummyClause(c) for c in result_data['flagged_clauses']]
                st.success("⚡ Instant Demo Loaded (API Bypassed)")
            else:
                st.session_state.demo_active = False # Fallback if text was modified
        
        if not st.session_state.demo_active:
            # Live Groq API Call
            api_key = st.secrets.get("GROQ_API_KEY") or os.getenv("GROQ_API_KEY")
            if not api_key:
                st.error("Missing GROQ_API_KEY. Please add it to Streamlit Secrets or your .env file.")
                st.stop()
                
            analyzer = ClauseAnalyzer(api_key=api_key)
            with st.spinner("Lexrisk is scanning for predatory language..."):
                result = analyzer.analyze(st.session_state.contract_text)

        # ── Display Results ──
        st.divider()
        risk_class = f"risk-{result.risk_level.lower()}"
        st.markdown(f"### Overall Risk Score")
        st.markdown(
            f'<p class="{risk_class}">{result.risk_score}/100 — {result.risk_level}</p>',
            unsafe_allow_html=True
        )
        st.progress(result.risk_score / 100)

        # Recommendation
        rec_emoji = {"SIGN": "✅", "NEGOTIATE": "⚠️", "AVOID": "🚫"}.get(result.recommendation, "❓")
        st.info(f"{rec_emoji} **Recommendation:** {result.recommendation}")

        # Summary
        st.markdown(f"**Summary:** {result.summary}")

        # Flagged Clauses
        if result.flagged_clauses:
            st.divider()
            st.markdown(f"### 🚨 {len(result.flagged_clauses)} Flagged Clause(s)")
            for i, clause in enumerate(result.flagged_clauses, 1):
                with st.expander(f"{i}. {clause.category} — {clause.severity}"):
                    st.markdown(f"**Clause Text:**")
                    st.code(clause.clause_text, language=None)
                    st.markdown(f"**Plain English:** {clause.plain_english}")
                    st.markdown(f"**⚠️ Red Flag:** {clause.red_flag}")
        else:
            st.success("✅ No predatory clauses detected.")

        st.warning(f"⚖️ **Legal Notice:** {result.disclaimer}")

    except Exception as e:
        st.error(f"Analysis failed: {e}")

# ── 11. Footer ────────────────────────────────────────────────────────────────
st.divider()
st.caption("🔒 **Privacy:** Data is analyzed in memory and immediately discarded. No storage.")
st.caption("⚖️ **Legal:** Lexrisk is an AI tool, not a law firm. No legal advice provided.")

st.markdown("""
<div style='text-align: center; color: #666; font-size: 0.75rem; padding: 2rem 0;'>
    <p><strong>CLAUSE</strong> by Babylon Technologies</p>
    <p>© 2026 Babylon Technologies. Building in public.</p>
    <p><a href="https://babylontech.org" style="color: #c9a84c;">Back to Babylon Studio</a></p>
</div>
""", unsafe_allow_html=True)
