
"""
app.py — Lexrisk: AI-powered predatory clause scanner
Run: streamlit run app.py
"""

import logging
import os
import sys
import pdfplumber
import streamlit as st
from dotenv import load_dotenv
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# ── 1. Page Config (MUST BE FIRST STREAMLIT COMMAND) ──────────────────────────
st.set_page_config(
    page_title="Lexrisk ⚖️",
    page_icon="⚖️",
    layout="centered",
    initial_sidebar_state="expanded",
)

# ── 2. Local Imports & Config ─────────────────────────────────────────────────
sys.path.insert(0, os.path.dirname(__file__))
from analyzer import ClauseAnalyzer
from demo_data import DEMOS  
from rate_limiter import get_user_id, check_rate_limit, increment_usage # <-- Rate Limiter Added

# Initialize sentence transformer for semantic chunking
sentence_model = SentenceTransformer('all-MiniLM-L6-v2')

load_dotenv()
logging.basicConfig(level=os.getenv("LOG_LEVEL", "INFO"))

# ── 3. Session State Initialization ───────────────────────────────────────────
if 'contract_text' not in st.session_state:
    st.session_state.contract_text = ""
if 'demo_active' not in st.session_state:
    st.session_state.demo_active = False

# ── 4. Styles & Branding Removal (Nuclear Ghost Mode) ─────────────────────────
st.markdown("""
<style>
    /* Hide the top header (hamburger, fork, deploy buttons) */
    header {visibility: hidden !important;}
    [data-testid="stHeader"] {visibility: hidden !important;}
    [data-testid="stToolbar"] {visibility: hidden !important;}
    
    /* Hide the main menu */
    #MainMenu {visibility: hidden !important;}
    
    /* Hide the footer (Made with Streamlit) */
    footer {visibility: hidden !important;}
    
    /* 🔴 THE 'HOSTED WITH STREAMLIT' BADGE NUCLEAR OPTION 🔴 */
    [data-testid="viewerBadge"] {display: none !important;}
    div[class^="viewerBadge"] {display: none !important;}
    div[class*="viewerBadge"] {display: none !important;}
    a[href*="streamlit.io/cloud"] {display: none !important;}
    a[href^="https://streamlit.io/cloud"] {display: none !important;}
    
    /* Move content up slightly to fill the blank space left by the header */
    .block-container {
        padding-top: 2rem;
        padding-bottom: 2rem;
    }

    /* Custom Risk Colors */
    .risk-critical { color: #ff4444; font-weight: bold; font-size: 1.5rem; }
    .risk-high     { color: #ff8800; font-weight: bold; font-size: 1.5rem; }
    .risk-medium   { color: #ffcc00; font-weight: bold; font-size: 1.5rem; }
    .risk-low      { color: #44cc44; font-weight: bold; font-size: 1.5rem; }
    .clause-card   { background: #1a1a2e; padding: 1rem; border-radius: 8px; margin: 0.5rem 0; }
</style>
""", unsafe_allow_html=True)

# ── 5. Sidebar Demos (Zero Latency) ───────────────────────────────────────────
st.sidebar.markdown("### ⚡ Instant Demos")
st.sidebar.caption("Pre-computed to bypass API limits during launch.")

def load_frozen_demo(demo_key):
    st.session_state.contract_text = DEMOS[demo_key]['text']
    st.session_state.demo_active = True

if st.sidebar.button("📱 Analyze TikTok ToS", use_container_width=True):
    load_frozen_demo('tiktok')
if st.sidebar.button("🐦 Analyze X ToS", use_container_width=True):
    load_frozen_demo('x_tos')
if st.sidebar.button("🏋️ Analyze Gym Contract", use_container_width=True):
    load_frozen_demo('gym')
if st.sidebar.button("💼 Analyze Startup NDA", use_container_width=True):
    load_frozen_demo('nda')

# Demo Alignment: Update hardcoded example to match new output format
st.sidebar.markdown("### 📋 Example Contract")
st.sidebar.caption("Example contract text for testing.")

# ── 6. Main Header (Hero Section) ─────────────────────────────────────────────
st.title("⚖️ Lexrisk")
st.markdown("### Don't Just Agree. Understand.")
st.markdown("""
Lexrisk uses high-intelligence AI to scan your contracts for predatory clauses in seconds.

**How it works:**
1. **Paste** your contract or upload a PDF below.
2. **Analyze** the text to identify hidden "Red Flag" clauses.
3. **Review** your simplified, plain-English risk report.
""")
st.caption("AI Safety Gauge for Predatory Legal Contracts — *By Babylon Technologies*")
st.warning("""
⚠️ **Disclaimer:** Lexrisk is an AI analysis tool, not a substitute for legal advice. 
Results are generated by AI and may contain errors. Always consult a qualified attorney 
before making decisions based on this analysis. By using this tool, you acknowledge that 
Babylon Technologies provides this service "as is" without warranties.
""")
st.divider()

# ── 7. PDF Uploader (World-Class Feature) ─────────────────────────────────────
st.markdown("### 📄 Upload a Contract (PDF)")
uploaded_file = st.file_uploader("Drag and drop a PDF file here to scan", type="pdf")

if uploaded_file is not None:
    try:
        # Use pdfplumber to count pages
        with pdfplumber.open(uploaded_file) as pdf:
            page_count = len(pdf.pages)
        
        if page_count > 2:
            st.warning(f"⚠️ PDF has {page_count} pages. For security, please sign up for authorized access to analyze longer documents.")
            st.link_button("Sign Up for Authorized Access", "/signup")
            st.stop()
        
        # Extract text using pdfplumber
        with pdfplumber.open(uploaded_file) as pdf:
            extracted_text = ""
            for page in pdf.pages:
                extracted_text += page.extract_text() + "\n"
        
        # Inject the PDF text directly into the scanner's session state
        st.session_state.contract_text = extracted_text
        st.session_state.demo_active = False # Disable demo bypass for new uploads
        st.success(f"✅ PDF Extracted Successfully! ({page_count} pages) Scroll down to review and analyze.")
    except Exception as e:
        st.error(f"Error reading PDF: {e}")

st.markdown("---")

# ── 8. Main Input Area ────────────────────────────────────────────────────────
contract_text = st.text_area(
    "Paste your contract or Terms of Service here",
    value=st.session_state.contract_text,
    height=300,
    placeholder="Paste any TOS, contract, or legal agreement...",
)

# Sync the text area back to session state if the user types manually
if contract_text != st.session_state.contract_text:
    st.session_state.contract_text = contract_text
    st.session_state.demo_active = False  # They edited it, so it's no longer a pure demo

# ── 9. Clickwrap & Analysis Trigger ───────────────────────────────────────────
st.markdown("---")
agreed = st.checkbox(
    "I understand Lexrisk is an AI tool and not a substitute for professional legal advice. "
    "I agree to the Terms of Service and Privacy Policy."
)

col1, col2 = st.columns([1, 2])
with col1:
    analyze_btn = st.button(
        "🔍 Analyze", 
        type="primary", 
        use_container_width=True, 
        disabled=not agreed
    )

if not agreed:
    st.info("💡 Please check the box above to enable the analysis.")

# ── 10. Core Analysis Logic (With Rate Limiting) ──────────────────────────────
if analyze_btn and st.session_state.contract_text.strip():
    try:
        # Check if we are running a frozen demo or a live API call
        if st.session_state.demo_active:
            # Bypass Groq entirely, use the frozen data based on matching text
            demo_match = next((d['analysis'] for d in DEMOS.values() if d['text'] == st.session_state.contract_text), None)
            if demo_match:
                result_data = demo_match
                # Reconstruct an object-like structure to match your analyzer output
                class DummyResult: pass
                result = DummyResult()
                result.risk_score = result_data['risk_score']
                result.risk_level = result_data['risk_level']
                result.summary = result_data['summary']
                result.recommendation = result_data['recommendation']
                result.disclaimer = "Lexrisk is an AI-powered assistant, not a legal professional. This analysis is for informational purposes only and does not constitute legal advice or an attorney-client relationship."
                
                class DummyClause:
                    def __init__(self, c):
                        self.category = c['category']
                        self.severity = c['severity']
                        self.clause_text = c['clause_text']
                        self.plain_english = c['plain_english']
                        self.red_flag = c['red_flag']
                
                result.flagged_clauses = [DummyClause(c) for c in result_data['flagged_clauses']]
                st.success("⚡ Instant Demo Loaded (API Bypassed)")
            else:
                st.session_state.demo_active = False # Fallback if text was modified
        
        if not st.session_state.demo_active:
            
            # --- 🛡️ RATE LIMIT CHECK 🛡️ ---
            user_id = get_user_id()
            allowed, remaining, reset_time = check_rate_limit(user_id, limit_type="analysis", max_daily=3)
            
            if not allowed:
                st.error("🛑 Daily scan limit reached. Please try again tomorrow.")
                st.stop() # Stops execution right here, protecting your API

            # API Rerouting Logic
            api_key = st.secrets.get("GROQ_API_KEY") or os.getenv("GROQ_API_KEY")
            if not api_key:
                st.error("Missing GROQ_API_KEY. Please add it to Streamlit Secrets or your .env file.")
                st.stop()
            
            # Check if we have a longer document (authorized user scenario)
            # For now, we'll use a simple flag or environment variable to determine authorization
            # In a real app, this would come from user authentication
            is_authorized_user = os.getenv("AUTHORIZED_USER", "false").lower() == "true"
            
            if is_authorized_user and len(st.session_state.contract_text.split()) > 1000:  # Rough word count check
                # Use Gemini 1.5 Pro for long documents (authorized users)
                # Note: This would require implementing a Gemini client
                st.info("Using Gemini 1.5 Pro for long document analysis...")
                # analyzer = GeminiAnalyzer(api_key=gemini_api_key)
            else:
                # Use Groq (Llama-3-70B) for standard analysis
                analyzer = ClauseAnalyzer(api_key=api_key)
            
            with st.spinner(f"Lexrisk is scanning for predatory language... ({remaining} scans remaining today)"):
                result = analyzer.analyze(st.session_state.contract_text)
                
            # If the analysis succeeds without throwing an error, increment the usage
            increment_usage(user_id, limit_type="analysis")

        # ── Display Results ──
        st.divider()
        risk_class = f"risk-{result.risk_level.lower()}"
        st.markdown(f"### Overall Risk Score")
        st.markdown(
            f'<p class="{risk_class}">{result.risk_score}/100 — {result.risk_level}</p>',
            unsafe_allow_html=True
        )
        st.progress(result.risk_score / 100)

        # Data Visualization: Risk Level Metric
        col1, col2, col3 = st.columns(3)
        with col1:
            st.metric("Risk Level", result.risk_level, delta=None)
        with col2:
            st.metric("Score", f"{result.risk_score}/100", delta=None)
        with col3:
            st.metric("Recommendation", result.recommendation, delta=None)

        # Recommendation
        rec_emoji = {"SIGN": "✅", "NEGOTIATE": "⚠️", "AVOID": "🚫"}.get(result.recommendation, "❓")
        st.info(f"{rec_emoji} **Recommendation:** {result.recommendation}")

        # Summary
        st.markdown(f"**Summary:** {result.summary}")

        # Flagged Clauses
        if result.flagged_clauses:
            st.divider()
            st.markdown(f"### 🚨 {len(result.flagged_clauses)} Flagged Clause(s)")
            for i, clause in enumerate(result.flagged_clauses, 1):
                with st.expander(f"{i}. {clause.category} — {clause.severity}"):
                    st.markdown(f"**Clause Text:**")
                    st.code(clause.clause_text, language=None)
                    st.markdown(f"**Plain English:** {clause.plain_english}")
                    st.markdown(f"**⚠️ Red Flag:** {clause.red_flag}")
        else:
            st.success("✅ No predatory clauses detected.")

        st.warning(f"⚖️ **Legal Notice:** {result.disclaimer}")

    except Exception as e:
        st.error(f"Analysis failed: {e}")

# ── 11. Footer ────────────────────────────────────────────────────────────────
st.divider()
st.caption("🔒 **Privacy:** Data is analyzed in memory and immediately discarded. No storage.")
st.caption("⚖️ **Legal:** Lexrisk is an AI tool, not a law firm. No legal advice provided.")

st.markdown("""
<div style='text-align: center; color: #666; font-size: 0.75rem; padding: 2rem 0;'>
    <p><strong>CLAUSE</strong> by Babylon Technologies</p>
    <p>© 2026 Babylon Technologies. Building in public.</p>
    <p><a href="https://bablyontech.org" style="color: #c9a84c;">Back to Babylon Studio</a></p>
</div>
""", unsafe_allow_html=True)
